name: Testflow
on:
  pull_request:
   branches: ["master"]

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      # Set up Flutter.
      - uses: actions/checkout@v3
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor -v

      - name: Get pub packages
        run: flutter pub get

      - name: Linter
        run: flutter analyze

      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Run Flutter widget test
        run: flutter test test/widget_test.dart